---
- name: Ubuntu Package Clean and Upgrade
  hosts: splunk 
  become: true
  tasks:
    - name: Ubuntu Package Clean and Upgrade
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: full

